name: Flask App Tests

on:
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./app/

        strategy:
            matrix:
                python-version: [3.8]

        env:   
            APP_MODE: production
            FLASK_HOST: 0.0.0.0
            FLASK_PORT: 8000
            FLASK_DEBUG: 1

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Set up python
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r ../requirements.txt

            - name: Test App Code
              run: python ./main_test.py
